name: pytest
on: push

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.11.6]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up rye
      uses: atu4403/setup-rye-multiOS@v1
    - name: Sync dependencies using rye
      run: |
        rye pin ${{ matrix.python-version }}
        rye sync
    - name: Pytest and Coverage
      run: |
        rye run coverage run -m --source=stacosys pytest tests
        rye run coverage report
    - name: Send report to Coveralls
      run: rye run coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
