name: pytest
on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.13.1]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    - name: Sync dependencies using uv
      run: |
        uv python pin ${{ matrix.python-version }}
        uv sync
    - name: Pytest and Coverage
      run: |
        PYTHONPATH=src/ uv run coverage run -m --source=stacosys pytest tests
        uv run coverage report
    - name: Send report to Coveralls
      run: uv run coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
